//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardProcessingApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Merchant()
        {
            this.MerchantInvitations = new HashSet<MerchantInvitation>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int MerchantId { get; set; }
        public int MerchantType { get; set; }
        public int ProvinceId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public bool IsActive { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<System.DateTime> FirstActiveDate { get; set; }
        public Nullable<System.DateTime> LastActiveDate { get; set; }
        public string MerchantName { get; set; }
        public string Status { get; set; }
        public string Owner { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Zip { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string BankCardDBA { get; set; }
        public string BackendProcessor { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual District District { get; set; }
        public virtual MerchantType MerchantType1 { get; set; }
        public virtual Province Province { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MerchantInvitation> MerchantInvitations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
