//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardProcessingApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public int MerchantId { get; set; }
        public string Address { get; set; }
        public int MerchantType { get; set; }
        public int ProvinceId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public bool IsActive { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<System.DateTime> FirstActiveDate { get; set; }
        public Nullable<System.DateTime> LastActiveDate { get; set; }
        public string MerchantName { get; set; }
        public string Status { get; set; }
        public string Owner { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Zip { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string BankCardDBA { get; set; }
    }
}
