//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardProcessingApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public System.DateTime NotificationTime { get; set; }
        public Nullable<int> FromMerchant { get; set; }
        public Nullable<int> FromAgent { get; set; }
        public Nullable<int> FromMaster { get; set; }
        public string ToMerchant { get; set; }
        public string ToAgent { get; set; }
        public string ToMaster { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsSeen { get; set; }
    }
}
