//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardProcessingApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int TransactionCode { get; set; }
        public int MerchantNumber { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public System.TimeSpan TransationTime { get; set; }
        public string Description { get; set; }
        public int CardTypeId { get; set; }
        public string KeyedEntry { get; set; }
        public int AuthorizationNumber { get; set; }
        public string AccountNumber { get; set; }
        public string FirstTwelveAccountNumber { get; set; }
        public string CountryCode { get; set; }
    }
}
